Enable codeql analysis
G-Research/consuldotnet pull request #107
Opened 2021-07-16 05:50 UTC by ljubon

Example run: https://github.com/ljubon/consuldotnet/actions/runs/1036400778
View alerts: https://imgur.com/a/3KT6XWD

2021-07-16 10:14 UTC, jgiannuzzi commented on .github/workflows/codeql-analysis.yml
> +        consul: [1.6.10, 1.7.14, 1.8.13, 1.9.7, 1.10.0]
I think there is no need to use a matrix for `framework` and `consul`. `framework` is used in the main CI pipeline to parallelise jobs, and `consul` is used to determine which version of the Consul agent to run the tests against. Here we don't run the tests, but instead we just want to build the entire solution for all frameworks (for which autobuild should actually be enough I guess).

2021-07-23 08:30 UTC, mfkl commented
Examples of CodeQL errors on Consul server source code on lgtm.com (powered by CodeQL) https://lgtm.com/projects/g/hashicorp/consul?mode=list

2021-07-23 08:30 UTC, mfkl submitted a review, later dismissed

2021-07-23 08:40 UTC, jgiannuzzi requested changes
I would like the build step to be changed to either be autobuild or a very simple build of the entire solution for all farther frameworks with the latest .NET 5 SDK. No need to download Consul server.

2021-07-24 07:07 UTC, ljubon commented
> I would like the build step to be changed to either be autobuild or a very simple build of the entire solution for all farther frameworks with the latest .NET 5 SDK. No need to download Consul server.

hellou, it seems that `auto build works just fine
I've checked, it's using latest.NET 5.0
e.g GH Action https://github.com/ljubon/consuldotnet/runs/3149516224?check_suite_focus=true

2021-09-03 09:18 UTC, jgiannuzzi approved these changes

2021-09-03 10:17 UTC, merged

2021-09-03 10:18 UTC, jgiannuzzi commented
Thanks for your contribution @ljubon!