Adding documentation website
G-Research/consuldotnet pull request #200
Opened 2023-03-09 15:47 UTC by naskio

- Adding website at `docs/`.
- Updating `README.md`.
- Moving `logo/` folder and other markdown files into the website.
- Updating links to point to the new domain `consuldot.net`.
- Adding GitHub workflow to auto-deploy the website into Pages (The version being used in the website is extracted automatically from the latest tag).

# TODO
In order to deploy the website to GitHub Pages, we need to perform the following tasks:

- [ ] Merge this PR.
- [x] Configure DNS for the new domain `consuldot.net`.
- [x] Enable GitHub Pages.

2023-03-10 07:42 UTC, jgiannuzzi commented
This looks awesome, thank you so much for your contribution @naskio! 🤩

@pavlovic-ivan could you please review the workflow?
@mfkl @marcin-krystianc could you please review the content?
@c-rindi could you please setup the domain?

2023-03-10 08:08 UTC, jgiannuzzi commented
I have enabled GitHub Pages for the repo.

2023-03-10 08:28 UTC, marcin-krystianc approved these changes
It looks great, thanks!

2023-03-10 12:47 UTC, mfkl submitted a review, later dismissed

2023-03-10 21:05 UTC, c-rindi commented
I have the set up the DNS - CNAME record. 
Thanks for good work @naskio and the clear instructions @jgiannuzzi. 😄

2023-03-10 21:33 UTC, jgiannuzzi commented
@c-rindi I missed one instruction 😓 — could you please add a similar `CNAME` for the `www` subdomain?

2023-03-14 14:17 UTC, pavlovic-ivan requested changes
@naskio thank you for the PR. one small change required before i approve. the rest looks good to me!

2023-03-14 14:17 UTC, pavlovic-ivan commented on .github/workflows/deploy-website.yml
> +    branches: [ $default-branch ]
@naskio the `$default-branch` is not supported currently in Github, you have to list the name of the default branch explicitly.

2023-03-14 14:51 UTC, pavlovic-ivan approved these changes
@naskio looks good. thanks 🙏

2023-03-18 15:37 UTC, jgiannuzzi commented
Thanks @c-rindi, the DNS checks are now successful!

Thank you @marcin-krystianc, @mfkl, and @pavlovic-ivan for your reviews, and most importantly thank you @naskio for this amazing contribution!

2023-03-18 16:37 UTC, merged

2023-03-18 16:56 UTC, jgiannuzzi commented
Great point @naskio — done!